<script>
  import * as Icon from "$lib";
</script>

<Icon.AcademicCapOutline size="40" variation="solid" />
<Icon.AcademicCapSolid size="40" variation="solid" />
<Icon.AdjustmentsOutline size="40" variation="solid" />
<Icon.AdjustmentsSolid size="40" variation="solid" />
<Icon.AnnotationOutline size="40" variation="solid" />
<Icon.AnnotationSolid size="40" variation="solid" />
<Icon.ArchiveOutline size="40" variation="solid" />
<Icon.ArchiveSolid size="40" variation="solid" />
<Icon.ArrowCircleDownOutline size="40" variation="solid" />
<Icon.ArrowCircleDownSolid size="40" variation="solid" />
<Icon.ArrowCircleLeftOutline size="40" variation="solid" />
<Icon.ArrowCircleLeftSolid size="40" variation="solid" />
<Icon.ArrowCircleRightOutline size="40" variation="solid" />
<Icon.ArrowCircleRightSolid size="40" variation="solid" />
<Icon.ArrowCircleUpOutline size="40" variation="solid" />
<Icon.ArrowCircleUpSolid size="40" variation="solid" />
<Icon.ArrowDownOutline size="40" variation="solid" />
<Icon.ArrowDownSolid size="40" variation="solid" />
<Icon.ArrowLeftOutline size="40" variation="solid" />
<Icon.ArrowLeftSolid size="40" variation="solid" />
<Icon.ArrowNarrowDownOutline size="40" variation="solid" />
<Icon.ArrowNarrowDownSolid size="40" variation="solid" />
<Icon.ArrowNarrowLeftOutline size="40" variation="solid" />
<Icon.ArrowNarrowLeftSolid size="40" variation="solid" />
<Icon.ArrowNarrowRightOutline size="40" variation="solid" />
<Icon.ArrowNarrowRightSolid size="40" variation="solid" />
<Icon.ArrowNarrowUpOutline size="40" variation="solid" />
<Icon.ArrowNarrowUpSolid size="40" variation="solid" />
<Icon.ArrowRightOutline size="40" variation="solid" />
<Icon.ArrowRightSolid size="40" variation="solid" />
<Icon.ArrowSmDownOutline size="40" variation="solid" />
<Icon.ArrowSmDownSolid size="40" variation="solid" />
<Icon.ArrowSmLeftOutline size="40" variation="solid" />
<Icon.ArrowSmLeftSolid size="40" variation="solid" />
<Icon.ArrowSmRightOutline size="40" variation="solid" />
<Icon.ArrowSmRightSolid size="40" variation="solid" />
<Icon.ArrowSmUpOutline size="40" variation="solid" />
<Icon.ArrowSmUpSolid size="40" variation="solid" />
<Icon.ArrowUpOutline size="40" variation="solid" />
<Icon.ArrowUpSolid size="40" variation="solid" />
<Icon.ArrowsExpandOutline size="40" variation="solid" />
<Icon.ArrowsExpandSolid size="40" variation="solid" />
<Icon.AtSymbolOutline size="40" variation="solid" />
<Icon.AtSymbolSolid size="40" variation="solid" />
<Icon.BackspaceOutline size="40" variation="solid" />
<Icon.BackspaceSolid size="40" variation="solid" />
<Icon.BadgeCheckOutline size="40" variation="solid" />
<Icon.BadgeCheckSolid size="40" variation="solid" />
<Icon.BanOutline size="40" variation="solid" />
<Icon.BanSolid size="40" variation="solid" />
<Icon.BeakerOutline size="40" variation="solid" />
<Icon.BeakerSolid size="40" variation="solid" />
<Icon.BellOutline size="40" variation="solid" />
<Icon.BellSolid size="40" variation="solid" />
<Icon.BookOpenOutline size="40" variation="solid" />
<Icon.BookOpenSolid size="40" variation="solid" />
<Icon.BookmarkAltOutline size="40" variation="solid" />
<Icon.BookmarkAltSolid size="40" variation="solid" />
<Icon.BookmarkOutline size="40" variation="solid" />
<Icon.BookmarkSolid size="40" variation="solid" />
<Icon.BriefcaseOutline size="40" variation="solid" />
<Icon.BriefcaseSolid size="40" variation="solid" />
<Icon.CakeOutline size="40" variation="solid" />
<Icon.CakeSolid size="40" variation="solid" />
<Icon.CalculatorOutline size="40" variation="solid" />
<Icon.CalculatorSolid size="40" variation="solid" />
<Icon.CalendarOutline size="40" variation="solid" />
<Icon.CalendarSolid size="40" variation="solid" />
<Icon.CameraOutline size="40" variation="solid" />
<Icon.CameraSolid size="40" variation="solid" />
<Icon.CashOutline size="40" variation="solid" />
<Icon.CashSolid size="40" variation="solid" />
<Icon.ChartBarOutline size="40" variation="solid" />
<Icon.ChartBarSolid size="40" variation="solid" />
<Icon.ChartPieOutline size="40" variation="solid" />
<Icon.ChartPieSolid size="40" variation="solid" />
<Icon.ChartSquareBarOutline size="40" variation="solid" />
<Icon.ChartSquareBarSolid size="40" variation="solid" />
<Icon.ChatAlt2Outline size="40" variation="solid" />
<Icon.ChatAlt2Solid size="40" variation="solid" />
<Icon.ChatAltOutline size="40" variation="solid" />
<Icon.ChatAltSolid size="40" variation="solid" />
<Icon.ChatOutline size="40" variation="solid" />
<Icon.ChatSolid size="40" variation="solid" />
<Icon.CheckCircleOutline size="40" variation="solid" />
<Icon.CheckCircleSolid size="40" variation="solid" />
<Icon.CheckOutline size="40" variation="solid" />
<Icon.CheckSolid size="40" variation="solid" />
<Icon.ChevronDoubleDownOutline size="40" variation="solid" />
<Icon.ChevronDoubleDownSolid size="40" variation="solid" />
<Icon.ChevronDoubleLeftOutline size="40" variation="solid" />
<Icon.ChevronDoubleLeftSolid size="40" variation="solid" />
<Icon.ChevronDoubleRightOutline size="40" variation="solid" />
<Icon.ChevronDoubleRightSolid size="40" variation="solid" />
<Icon.ChevronDoubleUpOutline size="40" variation="solid" />
<Icon.ChevronDoubleUpSolid size="40" variation="solid" />
<Icon.ChevronDownOutline size="40" variation="solid" />
<Icon.ChevronDownSolid size="40" variation="solid" />
<Icon.ChevronLeftOutline size="40" variation="solid" />
<Icon.ChevronLeftSolid size="40" variation="solid" />
<Icon.ChevronRightOutline size="40" variation="solid" />
<Icon.ChevronRightSolid size="40" variation="solid" />
<Icon.ChevronUpOutline size="40" variation="solid" />
<Icon.ChevronUpSolid size="40" variation="solid" />
<Icon.ChipOutline size="40" variation="solid" />
<Icon.ChipSolid size="40" variation="solid" />
<Icon.ClipboardCheckOutline size="40" variation="solid" />
<Icon.ClipboardCheckSolid size="40" variation="solid" />
<Icon.ClipboardCopyOutline size="40" variation="solid" />
<Icon.ClipboardCopySolid size="40" variation="solid" />
<Icon.ClipboardListOutline size="40" variation="solid" />
<Icon.ClipboardListSolid size="40" variation="solid" />
<Icon.ClipboardOutline size="40" variation="solid" />
<Icon.ClipboardSolid size="40" variation="solid" />
<Icon.ClockOutline size="40" variation="solid" />
<Icon.ClockSolid size="40" variation="solid" />
<Icon.CloudDownloadOutline size="40" variation="solid" />
<Icon.CloudDownloadSolid size="40" variation="solid" />
<Icon.CloudOutline size="40" variation="solid" />
<Icon.CloudSolid size="40" variation="solid" />
<Icon.CloudUploadOutline size="40" variation="solid" />
<Icon.CloudUploadSolid size="40" variation="solid" />
<Icon.CodeOutline size="40" variation="solid" />
<Icon.CodeSolid size="40" variation="solid" />
<Icon.CogOutline size="40" variation="solid" />
<Icon.CogSolid size="40" variation="solid" />
<Icon.CollectionOutline size="40" variation="solid" />
<Icon.CollectionSolid size="40" variation="solid" />
<Icon.ColorSwatchOutline size="40" variation="solid" />
<Icon.ColorSwatchSolid size="40" variation="solid" />
<Icon.CreditCardOutline size="40" variation="solid" />
<Icon.CreditCardSolid size="40" variation="solid" />
<Icon.CubeOutline size="40" variation="solid" />
<Icon.CubeSolid size="40" variation="solid" />
<Icon.CubeTransparentOutline size="40" variation="solid" />
<Icon.CubeTransparentSolid size="40" variation="solid" />
<Icon.CurrencyBangladeshiOutline size="40" variation="solid" />
<Icon.CurrencyBangladeshiSolid size="40" variation="solid" />
<Icon.CurrencyDollarOutline size="40" variation="solid" />
<Icon.CurrencyDollarSolid size="40" variation="solid" />
<Icon.CurrencyEuroOutline size="40" variation="solid" />
<Icon.CurrencyEuroSolid size="40" variation="solid" />
<Icon.CurrencyPoundOutline size="40" variation="solid" />
<Icon.CurrencyPoundSolid size="40" variation="solid" />
<Icon.CurrencyRupeeOutline size="40" variation="solid" />
<Icon.CurrencyRupeeSolid size="40" variation="solid" />
<Icon.CurrencyYenOutline size="40" variation="solid" />
<Icon.CurrencyYenSolid size="40" variation="solid" />
<Icon.CursorClickOutline size="40" variation="solid" />
<Icon.CursorClickSolid size="40" variation="solid" />
<Icon.DatabaseOutline size="40" variation="solid" />
<Icon.DatabaseSolid size="40" variation="solid" />
<Icon.DesktopComputerOutline size="40" variation="solid" />
<Icon.DesktopComputerSolid size="40" variation="solid" />
<Icon.DeviceMobileOutline size="40" variation="solid" />
<Icon.DeviceMobileSolid size="40" variation="solid" />
<Icon.DeviceTabletOutline size="40" variation="solid" />
<Icon.DeviceTabletSolid size="40" variation="solid" />
<Icon.DocumentAddOutline size="40" variation="solid" />
<Icon.DocumentAddSolid size="40" variation="solid" />
<Icon.DocumentDownloadOutline size="40" variation="solid" />
<Icon.DocumentDownloadSolid size="40" variation="solid" />
<Icon.DocumentDuplicateOutline size="40" variation="solid" />
<Icon.DocumentDuplicateSolid size="40" variation="solid" />
<Icon.DocumentOutline size="40" variation="solid" />
<Icon.DocumentRemoveOutline size="40" variation="solid" />
<Icon.DocumentRemoveSolid size="40" variation="solid" />
<Icon.DocumentReportOutline size="40" variation="solid" />
<Icon.DocumentReportSolid size="40" variation="solid" />
<Icon.DocumentSearchOutline size="40" variation="solid" />
<Icon.DocumentSearchSolid size="40" variation="solid" />
<Icon.DocumentSolid size="40" variation="solid" />
<Icon.DocumentTextOutline size="40" variation="solid" />
<Icon.DocumentTextSolid size="40" variation="solid" />
<Icon.DotsCircleHorizontalOutline size="40" variation="solid" />
<Icon.DotsCircleHorizontalSolid size="40" variation="solid" />
<Icon.DotsHorizontalOutline size="40" variation="solid" />
<Icon.DotsHorizontalSolid size="40" variation="solid" />
<Icon.DotsVerticalOutline size="40" variation="solid" />
<Icon.DotsVerticalSolid size="40" variation="solid" />
<Icon.DownloadOutline size="40" variation="solid" />
<Icon.DownloadSolid size="40" variation="solid" />
<Icon.DuplicateOutline size="40" variation="solid" />
<Icon.DuplicateSolid size="40" variation="solid" />
<Icon.EmojiHappyOutline size="40" variation="solid" />
<Icon.EmojiHappySolid size="40" variation="solid" />
<Icon.EmojiSadOutline size="40" variation="solid" />
<Icon.EmojiSadSolid size="40" variation="solid" />
<Icon.ExclamationCircleOutline size="40" variation="solid" />
<Icon.ExclamationCircleSolid size="40" variation="solid" />
<Icon.ExclamationOutline size="40" variation="solid" />
<Icon.ExclamationSolid size="40" variation="solid" />
<Icon.ExternalLinkOutline size="40" variation="solid" />
<Icon.ExternalLinkSolid size="40" variation="solid" />
<Icon.EyeOffOutline size="40" variation="solid" />
<Icon.EyeOffSolid size="40" variation="solid" />
<Icon.EyeOutline size="40" variation="solid" />
<Icon.EyeSolid size="40" variation="solid" />
<Icon.FastForwardOutline size="40" variation="solid" />
<Icon.FastForwardSolid size="40" variation="solid" />
<Icon.FilmOutline size="40" variation="solid" />
<Icon.FilmSolid size="40" variation="solid" />
<Icon.FilterOutline size="40" variation="solid" />
<Icon.FilterSolid size="40" variation="solid" />
<Icon.FingerPrintOutline size="40" variation="solid" />
<Icon.FingerPrintSolid size="40" variation="solid" />
<Icon.FireOutline size="40" variation="solid" />
<Icon.FireSolid size="40" variation="solid" />
<Icon.FlagOutline size="40" variation="solid" />
<Icon.FlagSolid size="40" variation="solid" />
<Icon.FolderAddOutline size="40" variation="solid" />
<Icon.FolderAddSolid size="40" variation="solid" />
<Icon.FolderDownloadOutline size="40" variation="solid" />
<Icon.FolderDownloadSolid size="40" variation="solid" />
<Icon.FolderOpenOutline size="40" variation="solid" />
<Icon.FolderOpenSolid size="40" variation="solid" />
<Icon.FolderOutline size="40" variation="solid" />
<Icon.FolderRemoveOutline size="40" variation="solid" />
<Icon.FolderRemoveSolid size="40" variation="solid" />
<Icon.FolderSolid size="40" variation="solid" />
<Icon.GiftOutline size="40" variation="solid" />
<Icon.GiftSolid size="40" variation="solid" />
<Icon.GlobeAltOutline size="40" variation="solid" />
<Icon.GlobeAltSolid size="40" variation="solid" />
<Icon.GlobeOutline size="40" variation="solid" />
<Icon.GlobeSolid size="40" variation="solid" />
<Icon.HandOutline size="40" variation="solid" />
<Icon.HandSolid size="40" variation="solid" />
<Icon.HashtagOutline size="40" variation="solid" />
<Icon.HashtagSolid size="40" variation="solid" />
<Icon.HeartOutline size="40" variation="solid" />
<Icon.HeartSolid size="40" variation="solid" />
<Icon.HomeOutline size="40" variation="solid" />
<Icon.HomeSolid size="40" variation="solid" />
<Icon.IdentificationOutline size="40" variation="solid" />
<Icon.IdentificationSolid size="40" variation="solid" />
<Icon.InboxInOutline size="40" variation="solid" />
<Icon.InboxInSolid size="40" variation="solid" />
<Icon.InboxOutline size="40" variation="solid" />
<Icon.InboxSolid size="40" variation="solid" />
<Icon.InformationCircleOutline size="40" variation="solid" />
<Icon.InformationCircleSolid size="40" variation="solid" />
<Icon.KeyOutline size="40" variation="solid" />
<Icon.KeySolid size="40" variation="solid" />
<Icon.LibraryOutline size="40" variation="solid" />
<Icon.LibrarySolid size="40" variation="solid" />
<Icon.LightBulbOutline size="40" variation="solid" />
<Icon.LightBulbSolid size="40" variation="solid" />
<Icon.LightningBoltOutline size="40" variation="solid" />
<Icon.LightningBoltSolid size="40" variation="solid" />
<Icon.LinkOutline size="40" variation="solid" />
<Icon.LinkSolid size="40" variation="solid" />
<Icon.LocationMarkerOutline size="40" variation="solid" />
<Icon.LocationMarkerSolid size="40" variation="solid" />
<Icon.LockClosedOutline size="40" variation="solid" />
<Icon.LockClosedSolid size="40" variation="solid" />
<Icon.LockOpenOutline size="40" variation="solid" />
<Icon.LockOpenSolid size="40" variation="solid" />
<Icon.LoginOutline size="40" variation="solid" />
<Icon.LoginSolid size="40" variation="solid" />
<Icon.LogoutOutline size="40" variation="solid" />
<Icon.LogoutSolid size="40" variation="solid" />
<Icon.MailOpenOutline size="40" variation="solid" />
<Icon.MailOpenSolid size="40" variation="solid" />
<Icon.MailOutline size="40" variation="solid" />
<Icon.MailSolid size="40" variation="solid" />
<Icon.MapOutline size="40" variation="solid" />
<Icon.MapSolid size="40" variation="solid" />
<Icon.MenuAlt1Outline size="40" variation="solid" />
<Icon.MenuAlt1Solid size="40" variation="solid" />
<Icon.MenuAlt2Outline size="40" variation="solid" />
<Icon.MenuAlt2Solid size="40" variation="solid" />
<Icon.MenuAlt3Outline size="40" variation="solid" />
<Icon.MenuAlt3Solid size="40" variation="solid" />
<Icon.MenuAlt4Outline size="40" variation="solid" />
<Icon.MenuAlt4Solid size="40" variation="solid" />
<Icon.MenuOutline size="40" variation="solid" />
<Icon.MenuSolid size="40" variation="solid" />
<Icon.MicrophoneOutline size="40" variation="solid" />
<Icon.MicrophoneSolid size="40" variation="solid" />
<Icon.MinusCircleOutline size="40" variation="solid" />
<Icon.MinusCircleSolid size="40" variation="solid" />
<Icon.MinusOutline size="40" variation="solid" />
<Icon.MinusSmOutline size="40" variation="solid" />
<Icon.MinusSmSolid size="40" variation="solid" />
<Icon.MinusSolid size="40" variation="solid" />
<Icon.MoonOutline size="40" variation="solid" />
<Icon.MoonSolid size="40" variation="solid" />
<Icon.MusicNoteOutline size="40" variation="solid" />
<Icon.MusicNoteSolid size="40" variation="solid" />
<Icon.NewspaperOutline size="40" variation="solid" />
<Icon.NewspaperSolid size="40" variation="solid" />
<Icon.OfficeBuildingOutline size="40" variation="solid" />
<Icon.OfficeBuildingSolid size="40" variation="solid" />
<Icon.PaperAirplaneOutline size="40" variation="solid" />
<Icon.PaperAirplaneSolid size="40" variation="solid" />
<Icon.PaperClipOutline size="40" variation="solid" />
<Icon.PaperClipSolid size="40" variation="solid" />
<Icon.PauseOutline size="40" variation="solid" />
<Icon.PauseSolid size="40" variation="solid" />
<Icon.PencilAltOutline size="40" variation="solid" />
<Icon.PencilAltSolid size="40" variation="solid" />
<Icon.PencilOutline size="40" variation="solid" />
<Icon.PencilSolid size="40" variation="solid" />
<Icon.PhoneIncomingOutline size="40" variation="solid" />
<Icon.PhoneIncomingSolid size="40" variation="solid" />
<Icon.PhoneMissedCallOutline size="40" variation="solid" />
<Icon.PhoneMissedCallSolid size="40" variation="solid" />
<Icon.PhoneOutgoingOutline size="40" variation="solid" />
<Icon.PhoneOutgoingSolid size="40" variation="solid" />
<Icon.PhoneOutline size="40" variation="solid" />
<Icon.PhoneSolid size="40" variation="solid" />
<Icon.PhotographOutline size="40" variation="solid" />
<Icon.PhotographSolid size="40" variation="solid" />
<Icon.PlayOutline size="40" variation="solid" />
<Icon.PlaySolid size="40" variation="solid" />
<Icon.PlusCircleOutline size="40" variation="solid" />
<Icon.PlusCircleSolid size="40" variation="solid" />
<Icon.PlusOutline size="40" variation="solid" />
<Icon.PlusSmOutline size="40" variation="solid" />
<Icon.PlusSmSolid size="40" variation="solid" />
<Icon.PlusSolid size="40" variation="solid" />
<Icon.PresentationChartBarOutline size="40" variation="solid" />
<Icon.PresentationChartBarSolid size="40" variation="solid" />
<Icon.PresentationChartLineOutline size="40" variation="solid" />
<Icon.PresentationChartLineSolid size="40" variation="solid" />
<Icon.PrinterOutline size="40" variation="solid" />
<Icon.PrinterSolid size="40" variation="solid" />
<Icon.PuzzleOutline size="40" variation="solid" />
<Icon.PuzzleSolid size="40" variation="solid" />
<Icon.QrcodeOutline size="40" variation="solid" />
<Icon.QrcodeSolid size="40" variation="solid" />
<Icon.QuestionMarkCircleOutline size="40" variation="solid" />
<Icon.QuestionMarkCircleSolid size="40" variation="solid" />
<Icon.ReceiptRefundOutline size="40" variation="solid" />
<Icon.ReceiptRefundSolid size="40" variation="solid" />
<Icon.ReceiptTaxOutline size="40" variation="solid" />
<Icon.ReceiptTaxSolid size="40" variation="solid" />
<Icon.RefreshOutline size="40" variation="solid" />
<Icon.RefreshSolid size="40" variation="solid" />
<Icon.ReplyOutline size="40" variation="solid" />
<Icon.ReplySolid size="40" variation="solid" />
<Icon.RewindOutline size="40" variation="solid" />
<Icon.RewindSolid size="40" variation="solid" />
<Icon.RssOutline size="40" variation="solid" />
<Icon.RssSolid size="40" variation="solid" />
<Icon.SaveAsOutline size="40" variation="solid" />
<Icon.SaveAsSolid size="40" variation="solid" />
<Icon.SaveOutline size="40" variation="solid" />
<Icon.SaveSolid size="40" variation="solid" />
<Icon.ScaleOutline size="40" variation="solid" />
<Icon.ScaleSolid size="40" variation="solid" />
<Icon.ScissorsOutline size="40" variation="solid" />
<Icon.ScissorsSolid size="40" variation="solid" />
<Icon.SearchCircleOutline size="40" variation="solid" />
<Icon.SearchCircleSolid size="40" variation="solid" />
<Icon.SearchOutline size="40" variation="solid" />
<Icon.SearchSolid size="40" variation="solid" />
<Icon.SelectorOutline size="40" variation="solid" />
<Icon.SelectorSolid size="40" variation="solid" />
<Icon.ServerOutline size="40" variation="solid" />
<Icon.ServerSolid size="40" variation="solid" />
<Icon.ShareOutline size="40" variation="solid" />
<Icon.ShareSolid size="40" variation="solid" />
<Icon.ShieldCheckOutline size="40" variation="solid" />
<Icon.ShieldCheckSolid size="40" variation="solid" />
<Icon.ShieldExclamationOutline size="40" variation="solid" />
<Icon.ShieldExclamationSolid size="40" variation="solid" />
<Icon.ShoppingBagOutline size="40" variation="solid" />
<Icon.ShoppingBagSolid size="40" variation="solid" />
<Icon.ShoppingCartOutline size="40" variation="solid" />
<Icon.ShoppingCartSolid size="40" variation="solid" />
<Icon.SortAscendingOutline size="40" variation="solid" />
<Icon.SortAscendingSolid size="40" variation="solid" />
<Icon.SortDescendingOutline size="40" variation="solid" />
<Icon.SortDescendingSolid size="40" variation="solid" />
<Icon.SparklesOutline size="40" variation="solid" />
<Icon.SparklesSolid size="40" variation="solid" />
<Icon.SpeakerphoneOutline size="40" variation="solid" />
<Icon.SpeakerphoneSolid size="40" variation="solid" />
<Icon.StarOutline size="40" variation="solid" />
<Icon.StarSolid size="40" variation="solid" />
<Icon.StatusOfflineOutline size="40" variation="solid" />
<Icon.StatusOfflineSolid size="40" variation="solid" />
<Icon.StatusOnlineOutline size="40" variation="solid" />
<Icon.StatusOnlineSolid size="40" variation="solid" />
<Icon.StopOutline size="40" variation="solid" />
<Icon.StopSolid size="40" variation="solid" />
<Icon.SunOutline size="40" variation="solid" />
<Icon.SunSolid size="40" variation="solid" />
<Icon.SupportOutline size="40" variation="solid" />
<Icon.SupportSolid size="40" variation="solid" />
<Icon.SwitchHorizontalOutline size="40" variation="solid" />
<Icon.SwitchHorizontalSolid size="40" variation="solid" />
<Icon.SwitchVerticalOutline size="40" variation="solid" />
<Icon.SwitchVerticalSolid size="40" variation="solid" />
<Icon.TableOutline size="40" variation="solid" />
<Icon.TableSolid size="40" variation="solid" />
<Icon.TagOutline size="40" variation="solid" />
<Icon.TagSolid size="40" variation="solid" />
<Icon.TemplateOutline size="40" variation="solid" />
<Icon.TemplateSolid size="40" variation="solid" />
<Icon.TerminalOutline size="40" variation="solid" />
<Icon.TerminalSolid size="40" variation="solid" />
<Icon.ThumbDownOutline size="40" variation="solid" />
<Icon.ThumbDownSolid size="40" variation="solid" />
<Icon.ThumbUpOutline size="40" variation="solid" />
<Icon.ThumbUpSolid size="40" variation="solid" />
<Icon.TicketOutline size="40" variation="solid" />
<Icon.TicketSolid size="40" variation="solid" />
<Icon.TranslateOutline size="40" variation="solid" />
<Icon.TranslateSolid size="40" variation="solid" />
<Icon.TrashOutline size="40" variation="solid" />
<Icon.TrashSolid size="40" variation="solid" />
<Icon.TrendingDownOutline size="40" variation="solid" />
<Icon.TrendingDownSolid size="40" variation="solid" />
<Icon.TrendingUpOutline size="40" variation="solid" />
<Icon.TrendingUpSolid size="40" variation="solid" />
<Icon.TruckOutline size="40" variation="solid" />
<Icon.TruckSolid size="40" variation="solid" />
<Icon.UploadOutline size="40" variation="solid" />
<Icon.UploadSolid size="40" variation="solid" />
<Icon.UserAddOutline size="40" variation="solid" />
<Icon.UserAddSolid size="40" variation="solid" />
<Icon.UserCircleOutline size="40" variation="solid" />
<Icon.UserCircleSolid size="40" variation="solid" />
<Icon.UserGroupOutline size="40" variation="solid" />
<Icon.UserGroupSolid size="40" variation="solid" />
<Icon.UserOutline size="40" variation="solid" />
<Icon.UserRemoveOutline size="40" variation="solid" />
<Icon.UserRemoveSolid size="40" variation="solid" />
<Icon.UserSolid size="40" variation="solid" />
<Icon.UsersOutline size="40" variation="solid" />
<Icon.UsersSolid size="40" variation="solid" />
<Icon.VariableOutline size="40" variation="solid" />
<Icon.VariableSolid size="40" variation="solid" />
<Icon.VideoCameraOutline size="40" variation="solid" />
<Icon.VideoCameraSolid size="40" variation="solid" />
<Icon.ViewBoardsOutline size="40" variation="solid" />
<Icon.ViewBoardsSolid size="40" variation="solid" />
<Icon.ViewGridAddOutline size="40" variation="solid" />
<Icon.ViewGridAddSolid size="40" variation="solid" />
<Icon.ViewGridOutline size="40" variation="solid" />
<Icon.ViewGridSolid size="40" variation="solid" />
<Icon.ViewListOutline size="40" variation="solid" />
<Icon.ViewListSolid size="40" variation="solid" />
<Icon.VolumeOffOutline size="40" variation="solid" />
<Icon.VolumeOffSolid size="40" variation="solid" />
<Icon.VolumeUpOutline size="40" variation="solid" />
<Icon.VolumeUpSolid size="40" variation="solid" />
<Icon.WifiOutline size="40" variation="solid" />
<Icon.WifiSolid size="40" variation="solid" />
<Icon.XCircleOutline size="40" variation="solid" />
<Icon.XCircleSolid size="40" variation="solid" />
<Icon.XOutline size="40" variation="solid" />
<Icon.XSolid size="40" variation="solid" />
<Icon.ZoomInOutline size="40" variation="solid" />
<Icon.ZoomInSolid size="40" variation="solid" />
<Icon.ZoomOutOutline size="40" variation="solid" />
<Icon.ZoomOutSolid size="40" variation="solid" />
