<script>
  import * as Icon from "$lib";
  const random_hex_color_code = () => {
    let n = (Math.random() * 0xfffff * 1000000).toString(16);
    return "#" + n.slice(0, 6);
  };
</script>

<Icon.AcademicCap size="40" color={random_hex_color_code()} />
<Icon.Adjustments size="40" color={random_hex_color_code()} />
<Icon.Annotation size="40" color={random_hex_color_code()} />
<Icon.Archive size="40" color={random_hex_color_code()} />
<Icon.ArrowCircleDown size="40" color={random_hex_color_code()} />
<Icon.ArrowCircleLeft size="40" color={random_hex_color_code()} />
<Icon.ArrowCircleRight size="40" color={random_hex_color_code()} />
<Icon.ArrowCircleUp size="40" color={random_hex_color_code()} />
<Icon.ArrowDown size="40" color={random_hex_color_code()} />
<Icon.ArrowLeft size="40" color={random_hex_color_code()} />
<Icon.ArrowNarrowDown size="40" color={random_hex_color_code()} />
<Icon.ArrowNarrowLeft size="40" color={random_hex_color_code()} />
<Icon.ArrowNarrowRight size="40" color={random_hex_color_code()} />
<Icon.ArrowNarrowUp size="40" color={random_hex_color_code()} />
<Icon.ArrowRight size="40" color={random_hex_color_code()} />
<Icon.ArrowSmDown size="40" color={random_hex_color_code()} />
<Icon.ArrowSmLeft size="40" color={random_hex_color_code()} />
<Icon.ArrowSmRight size="40" color={random_hex_color_code()} />
<Icon.ArrowSmUp size="40" color={random_hex_color_code()} />
<Icon.ArrowUp size="40" color={random_hex_color_code()} />
<Icon.ArrowsExpand size="40" color={random_hex_color_code()} />
<Icon.AtSymbol size="40" color={random_hex_color_code()} />
<Icon.Backspace size="40" color={random_hex_color_code()} />
<Icon.BadgeCheck size="40" color={random_hex_color_code()} />
<Icon.Ban size="40" color={random_hex_color_code()} />
<Icon.Beaker size="40" color={random_hex_color_code()} />
<Icon.Bell size="40" color={random_hex_color_code()} />
<Icon.BookOpen size="40" color={random_hex_color_code()} />
<Icon.Bookmark size="40" color={random_hex_color_code()} />
<Icon.BookmarkAlt size="40" color={random_hex_color_code()} />
<Icon.Briefcase size="40" color={random_hex_color_code()} />
<Icon.Cake size="40" color={random_hex_color_code()} />
<Icon.Calculator size="40" color={random_hex_color_code()} />
<Icon.Calendar size="40" color={random_hex_color_code()} />
<Icon.Camera size="40" color={random_hex_color_code()} />
<Icon.Cash size="40" color={random_hex_color_code()} />
<Icon.ChartBar size="40" color={random_hex_color_code()} />
<Icon.ChartPie size="40" color={random_hex_color_code()} />
<Icon.ChartSquareBar size="40" color={random_hex_color_code()} />
<Icon.Chat size="40" color={random_hex_color_code()} />
<Icon.ChatAlt size="40" color={random_hex_color_code()} />
<Icon.ChatAlt2 size="40" color={random_hex_color_code()} />
<Icon.Check size="40" color={random_hex_color_code()} />
<Icon.CheckCircle size="40" color={random_hex_color_code()} />
<Icon.ChevronDoubleDown size="40" color={random_hex_color_code()} />
<Icon.ChevronDoubleLeft size="40" color={random_hex_color_code()} />
<Icon.ChevronDoubleRight size="40" color={random_hex_color_code()} />
<Icon.ChevronDoubleUp size="40" color={random_hex_color_code()} />
<Icon.ChevronDown size="40" color={random_hex_color_code()} />
<Icon.ChevronLeft size="40" color={random_hex_color_code()} />
<Icon.ChevronRight size="40" color={random_hex_color_code()} />
<Icon.ChevronUp size="40" color={random_hex_color_code()} />
<Icon.Chip size="40" color={random_hex_color_code()} />
<Icon.Clipboard size="40" color={random_hex_color_code()} />
<Icon.ClipboardCheck size="40" color={random_hex_color_code()} />
<Icon.ClipboardCopy size="40" color={random_hex_color_code()} />
<Icon.ClipboardList size="40" color={random_hex_color_code()} />
<Icon.Clock size="40" color={random_hex_color_code()} />
<Icon.Cloud size="40" color={random_hex_color_code()} />
<Icon.CloudDownload size="40" color={random_hex_color_code()} />
<Icon.CloudUpload size="40" color={random_hex_color_code()} />
<Icon.Code size="40" color={random_hex_color_code()} />
<Icon.Cog size="40" color={random_hex_color_code()} />
<Icon.Collection size="40" color={random_hex_color_code()} />
<Icon.ColorSwatch size="40" color={random_hex_color_code()} />
<Icon.CreditCard size="40" color={random_hex_color_code()} />
<Icon.Cube size="40" color={random_hex_color_code()} />
<Icon.CubeTransparent size="40" color={random_hex_color_code()} />
<Icon.CurrencyBangladeshi size="40" color={random_hex_color_code()} />
<Icon.CurrencyDollar size="40" color={random_hex_color_code()} />
<Icon.CurrencyEuro size="40" color={random_hex_color_code()} />
<Icon.CurrencyPound size="40" color={random_hex_color_code()} />
<Icon.CurrencyRupee size="40" color={random_hex_color_code()} />
<Icon.CurrencyYen size="40" color={random_hex_color_code()} />
<Icon.CursorClick size="40" color={random_hex_color_code()} />
<Icon.Database size="40" color={random_hex_color_code()} />
<Icon.DesktopComputer size="40" color={random_hex_color_code()} />
<Icon.DeviceMobile size="40" color={random_hex_color_code()} />
<Icon.DeviceTablet size="40" color={random_hex_color_code()} />
<Icon.Document size="40" color={random_hex_color_code()} />
<Icon.DocumentAdd size="40" color={random_hex_color_code()} />
<Icon.DocumentDownload size="40" color={random_hex_color_code()} />
<Icon.DocumentDuplicate size="40" color={random_hex_color_code()} />
<Icon.DocumentRemove size="40" color={random_hex_color_code()} />
<Icon.DocumentReport size="40" color={random_hex_color_code()} />
<Icon.DocumentSearch size="40" color={random_hex_color_code()} />
<Icon.DocumentText size="40" color={random_hex_color_code()} />
<Icon.DotsCircleHorizontal size="40" color={random_hex_color_code()} />
<Icon.DotsHorizontal size="40" color={random_hex_color_code()} />
<Icon.DotsVertical size="40" color={random_hex_color_code()} />
<Icon.Download size="40" color={random_hex_color_code()} />
<Icon.Duplicate size="40" color={random_hex_color_code()} />
<Icon.EmojiHappy size="40" color={random_hex_color_code()} />
<Icon.EmojiSad size="40" color={random_hex_color_code()} />
<Icon.Exclamation size="40" color={random_hex_color_code()} />
<Icon.ExclamationCircle size="40" color={random_hex_color_code()} />
<Icon.ExternalLink size="40" color={random_hex_color_code()} />
<Icon.Eye size="40" color={random_hex_color_code()} />
<Icon.EyeOff size="40" color={random_hex_color_code()} />
<Icon.FastForward size="40" color={random_hex_color_code()} />
<Icon.Film size="40" color={random_hex_color_code()} />
<Icon.Filter size="40" color={random_hex_color_code()} />
<Icon.FingerPrint size="40" color={random_hex_color_code()} />
<Icon.Fire size="40" color={random_hex_color_code()} />
<Icon.Flag size="40" color={random_hex_color_code()} />
<Icon.Folder size="40" color={random_hex_color_code()} />
<Icon.FolderAdd size="40" color={random_hex_color_code()} />
<Icon.FolderDownload size="40" color={random_hex_color_code()} />
<Icon.FolderOpen size="40" color={random_hex_color_code()} />
<Icon.FolderRemove size="40" color={random_hex_color_code()} />
<Icon.Gift size="40" color={random_hex_color_code()} />
<Icon.Globe size="40" color={random_hex_color_code()} />
<Icon.GlobeAlt size="40" color={random_hex_color_code()} />
<Icon.Hand size="40" color={random_hex_color_code()} />
<Icon.Hashtag size="40" color={random_hex_color_code()} />
<Icon.Heart size="40" color={random_hex_color_code()} />
<Icon.Home size="40" color={random_hex_color_code()} />
<Icon.Identification size="40" color={random_hex_color_code()} />
<Icon.Inbox size="40" color={random_hex_color_code()} />
<Icon.InboxIn size="40" color={random_hex_color_code()} />
<Icon.InformationCircle size="40" color={random_hex_color_code()} />
<Icon.Key size="40" color={random_hex_color_code()} />
<Icon.Library size="40" color={random_hex_color_code()} />
<Icon.LightBulb size="40" color={random_hex_color_code()} />
<Icon.LightningBolt size="40" color={random_hex_color_code()} />
<Icon.Link size="40" color={random_hex_color_code()} />
<Icon.LocationMarker size="40" color={random_hex_color_code()} />
<Icon.LockClosed size="40" color={random_hex_color_code()} />
<Icon.LockOpen size="40" color={random_hex_color_code()} />
<Icon.Login size="40" color={random_hex_color_code()} />
<Icon.Logout size="40" color={random_hex_color_code()} />
<Icon.Mail size="40" color={random_hex_color_code()} />
<Icon.MailOpen size="40" color={random_hex_color_code()} />
<Icon.Map size="40" color={random_hex_color_code()} />
<Icon.Menu size="40" color={random_hex_color_code()} />
<Icon.MenuAlt1 size="40" color={random_hex_color_code()} />
<Icon.MenuAlt2 size="40" color={random_hex_color_code()} />
<Icon.MenuAlt3 size="40" color={random_hex_color_code()} />
<Icon.MenuAlt4 size="40" color={random_hex_color_code()} />
<Icon.Microphone size="40" color={random_hex_color_code()} />
<Icon.Minus size="40" color={random_hex_color_code()} />
<Icon.MinusCircle size="40" color={random_hex_color_code()} />
<Icon.MinusSm size="40" color={random_hex_color_code()} />
<Icon.Moon size="40" color={random_hex_color_code()} />
<Icon.MusicNote size="40" color={random_hex_color_code()} />
<Icon.Newspaper size="40" color={random_hex_color_code()} />
<Icon.OfficeBuilding size="40" color={random_hex_color_code()} />
<Icon.PaperAirplane size="40" color={random_hex_color_code()} />
<Icon.PaperClip size="40" color={random_hex_color_code()} />
<Icon.Pause size="40" color={random_hex_color_code()} />
<Icon.Pencil size="40" color={random_hex_color_code()} />
<Icon.PencilAlt size="40" color={random_hex_color_code()} />
<Icon.Phone size="40" color={random_hex_color_code()} />
<Icon.PhoneIncoming size="40" color={random_hex_color_code()} />
<Icon.PhoneMissedCall size="40" color={random_hex_color_code()} />
<Icon.PhoneOutgoing size="40" color={random_hex_color_code()} />
<Icon.Photograph size="40" color={random_hex_color_code()} />
<Icon.Play size="40" color={random_hex_color_code()} />
<Icon.Plus size="40" color={random_hex_color_code()} />
<Icon.PlusCircle size="40" color={random_hex_color_code()} />
<Icon.PlusSm size="40" color={random_hex_color_code()} />
<Icon.PresentationChartBar size="40" color={random_hex_color_code()} />
<Icon.PresentationChartLine size="40" color={random_hex_color_code()} />
<Icon.Printer size="40" color={random_hex_color_code()} />
<Icon.Puzzle size="40" color={random_hex_color_code()} />
<Icon.Qrcode size="40" color={random_hex_color_code()} />
<Icon.QuestionMarkCircle size="40" color={random_hex_color_code()} />
<Icon.ReceiptRefund size="40" color={random_hex_color_code()} />
<Icon.ReceiptTax size="40" color={random_hex_color_code()} />
<Icon.Refresh size="40" color={random_hex_color_code()} />
<Icon.Reply size="40" color={random_hex_color_code()} />
<Icon.Rewind size="40" color={random_hex_color_code()} />
<Icon.Rss size="40" color={random_hex_color_code()} />
<Icon.Save size="40" color={random_hex_color_code()} />
<Icon.SaveAs size="40" color={random_hex_color_code()} />
<Icon.Scale size="40" color={random_hex_color_code()} />
<Icon.Scissors size="40" color={random_hex_color_code()} />
<Icon.Search size="40" color={random_hex_color_code()} />
<Icon.SearchCircle size="40" color={random_hex_color_code()} />
<Icon.Selector size="40" color={random_hex_color_code()} />
<Icon.Server size="40" color={random_hex_color_code()} />
<Icon.Share size="40" color={random_hex_color_code()} />
<Icon.ShieldCheck size="40" color={random_hex_color_code()} />
<Icon.ShieldExclamation size="40" color={random_hex_color_code()} />
<Icon.ShoppingBag size="40" color={random_hex_color_code()} />
<Icon.ShoppingCart size="40" color={random_hex_color_code()} />
<Icon.SortAscending size="40" color={random_hex_color_code()} />
<Icon.SortDescending size="40" color={random_hex_color_code()} />
<Icon.Sparkles size="40" color={random_hex_color_code()} />
<Icon.Speakerphone size="40" color={random_hex_color_code()} />
<Icon.Star size="40" color={random_hex_color_code()} />
<Icon.StatusOffline size="40" color={random_hex_color_code()} />
<Icon.StatusOnline size="40" color={random_hex_color_code()} />
<Icon.Stop size="40" color={random_hex_color_code()} />
<Icon.Sun size="40" color={random_hex_color_code()} />
<Icon.Support size="40" color={random_hex_color_code()} />
<Icon.SwitchHorizontal size="40" color={random_hex_color_code()} />
<Icon.SwitchVertical size="40" color={random_hex_color_code()} />
<Icon.Table size="40" color={random_hex_color_code()} />
<Icon.Tag size="40" color={random_hex_color_code()} />
<Icon.Template size="40" color={random_hex_color_code()} />
<Icon.Terminal size="40" color={random_hex_color_code()} />
<Icon.ThumbDown size="40" color={random_hex_color_code()} />
<Icon.ThumbUp size="40" color={random_hex_color_code()} />
<Icon.Ticket size="40" color={random_hex_color_code()} />
<Icon.Translate size="40" color={random_hex_color_code()} />
<Icon.Trash size="40" color={random_hex_color_code()} />
<Icon.TrendingDown size="40" color={random_hex_color_code()} />
<Icon.TrendingUp size="40" color={random_hex_color_code()} />
<Icon.Truck size="40" color={random_hex_color_code()} />
<Icon.Upload size="40" color={random_hex_color_code()} />
<Icon.User size="40" color={random_hex_color_code()} />
<Icon.UserAdd size="40" color={random_hex_color_code()} />
<Icon.UserCircle size="40" color={random_hex_color_code()} />
<Icon.UserGroup size="40" color={random_hex_color_code()} />
<Icon.UserRemove size="40" color={random_hex_color_code()} />
<Icon.Users size="40" color={random_hex_color_code()} />
<Icon.Variable size="40" color={random_hex_color_code()} />
<Icon.VideoCamera size="40" color={random_hex_color_code()} />
<Icon.ViewBoards size="40" color={random_hex_color_code()} />
<Icon.ViewGrid size="40" color={random_hex_color_code()} />
<Icon.ViewGridAdd size="40" color={random_hex_color_code()} />
<Icon.ViewList size="40" color={random_hex_color_code()} />
<Icon.VolumeOff size="40" color={random_hex_color_code()} />
<Icon.VolumeUp size="40" color={random_hex_color_code()} />
<Icon.Wifi size="40" color={random_hex_color_code()} />
<Icon.X size="40" color={random_hex_color_code()} />
<Icon.XCircle size="40" color={random_hex_color_code()} />
<Icon.ZoomIn size="40" color={random_hex_color_code()} />
<Icon.ZoomOut size="40" color={random_hex_color_code()} />
